export default {
  menu: {
    menu_title_1: 'Home',
    menu_title_2: 'Product Service',
    menu_title_3: 'Service for All',
    menu_title_4: 'About Siraya',
    menu_title_5: 'Contact us',
    menu_title_6: 'English',
    menu_info_2_1: 'Web Performance',
    menu_info_2_2: 'Web Security',
    menu_info_2_3: 'Data Intelligence',
    menu_info_2_4: 'Partner Network',
    menu_info_3_1: 'Service for All',
    menu_info_3_2: 'Partner Network',
    menu_info_4_1: 'Mission & Vision',
    menu_info_4_2: 'Contact Sales',
  },
  more: 'More',
  home_1: {
    row1_1: 'SPEED . SECURITY .',
    row1_2: 'SIMPLICITY',
    row1_3: 'Your Dedicated CDN & Cloud Secuirty Team',
    row1_4: 'Contact Sales',
    row1_5: 'Scroll Down',
  },
  home: {
    home_info_2_1: 'Service for All',
    home_info_2_2: 'From individual bloggers to fortune 500 enterprises, we provide our full attention to each and every client who is eager to thrive and win.',
    home_info_2_3: 'SMES',
    home_detail_2_1: 'We provide out-of-the-box solutions that are simple and effective for SMEs so they can have peace of mind and focus on developing core business competency',
    home_info_2_4: 'Saas',
    home_detail_2_2: 'Saas companies rely on SIRAYA to build highly customized solutions tailored to their specific business requirements',
    home_info_2_6: 'Online Gaming',
    home_detail_2_3: 'We have deep experience in providing online gaming customers with 24 x7 techincal support of the highest quality to ensure 100% uptime and optimal performance for any game applications',
    home_info_2_8: 'Media Entertainment',
    home_detail_2_4: 'Our media delivery solution suite helps media entertainment companies deliver a highly interactive, smooth and lightening fast viewing experience ',
    home_title_3_1: 'Products & Services',
    home_info_3_1: 'Web Performance',
    home_detail_3_1: 'China Acceleration, Global CDNs, VoD & Live Streaming Delivery, Cloud Storage & Image Optimisation',
    home_info_3_2: 'Web Security',
    home_detail_3_2: 'DDoS Mitigation, DNS Security, Bot Management, SSL, Access Control, Media Security',
    home_info_3_3: 'Data Intelligence',
    home_detail_3_3: 'Real-Time Performance Monitoring, Network Layer Analytics, App & Live,  Streaming Performance Monitoring, Layer3/4/7 Attack Analytics & Alerting',
    home_info_4_1: 'Partner Network',
    home_info_4_2: 'We have deep partnerships with some of the most innovative and robust technology providers in the market. Taking a vendor agnostic approach to serving our clients, we only believe in solutions that fit your unique need.',
  },
  partners: {
    partners_info_1: "Our",
    partners_info_2: "Partner",
    partners_info_3: "Our Partner Network",
    partners_info_4: "We work smoothly with some of the most innovative and robust technology providers, making sure our clients benefit from all.",
    partners_info_5: "Become Our Partner",
    partners_info_6: "Keen to become our partner?",
    partners_info_7: "We have abundant experiences working with world’s leading vendors in providing added technical value with our managed services, and other solutions.",
    partners_info_8: "Become Siraya’s Partner",
    partners_info_9: "First name",
    partners_info_10: "Last name",
    partners_info_11: "Company name",
    partners_info_12: "Phone number",
    partners_info_13: "Email",
    partners_info_14: "Message",
    partners_info_15: "Submit",
    partners_info_16: "Please complete this requlred field.",
  },
  contact: {
    contact_info_1: "Contact Sales",
    isSuccess: "Success",
    pop_title: "Contact Sales",
    pop_info: "We are customer obsessed and want to help you. Getting in touch with our Global Sales team is simple and fast. Just complete the form provided and we will contact you shortly."
  },
  foot: {
    foot_info_1: "20 Shaw Road, #05-08A,",
    foot_info_2: "Ching Shine Industrial Building, Singapore 367956",
    foot_info_3: "+65 6233 0988",
    foot_info_4: "siraya2022",
    foot_info_5: "sales@sirayatech.com",
    foot_info_6: "@siraya_official",
    foot_info_7: "support@sirayatech.com",
  },
  product: {
    product_1: "Products & Services",
    product_2: "Web Performance",
    product_3: "Web Security",
    product_4: "Data Intelligence",
    product_5: "Web Performance",
    product_6: "China Acceleration, Global CDNs, VoD & Live Streaming Delivery, Cloud Storage & Image Optimisation",
    product_7: "China Acceleration",
    product_8: "Restricted by Chinese Government’s stringent regulations on the internet, and the complexity of ISP ecosystem in China, most international CDN vendors or Cloud Service Providers have suboptimal interconnectivity within China. We provide ICP filing service, China domestic PoP coverage, CN2 connectivity, CPS premium route and other solutions to best accelerate your content delivery to eyeballs in China, so that your services can be connected smoothly in every corner of mainland China. ",
    product_9: "Global CDNs",
    product_10: "Siraya provides a global web acceleration solution to optimize the reach of your business to the world. With the extensive global network coverage and smart routing technology of our CDN service, we not only help speed up your web properties in all layers but provide network resource redundancy and minimize the impact of network issues on your business such as network outages and jitters. ",
    product_11: "VoD & Live Streaming Delivery",
    product_12: "Based on leading content import and network publishing and large-scale distributed real-time conversion technology, we will build a comprehensive video and audio live broadcast platform, and provide integrated solutions such as media storage, slice conversion, access authentication, and content transmission acceleration CDN/DCDN.",
    product_13: "Cloud Storage & Image Optimisation",
    product_14: "Object Storage is a reliable, high-performance, always-on data repository that empowers you to store unstructured data of any size and format, and then access it seamlessly from any location using the HTTP or HTTPS protocol.With high throughput and low latency, you can store, manage, and share massive amounts of data efficiently using our web portal, RESTful API, and SDKs. Whether you are looking to back up and restore data, archive information, distribute content, host static websites, or deliver media assets, Object Storage overcomes the inherent limitations of file systems to address today’s massive data challenges. Object Storage can be used alone or with other services to provide unprecedented levels of integration with our global content delivery network (CDN).",
    product_15: "Web Security",
    product_16: "DDoS Mitigation, DNS Security, Bot Management, SSL, Access Control, Media Security",
    product_17: "DDoS Mitigation",
    product_18: "Volumetric DDoS Mitigation",
    product_19: "L7 DDoS Mitigation",
    product_20: "DNS Security",
    product_21: "Anti Domain Hijacking",
    product_22: "DNS-level DDoS Protection",
    product_23: "Bot Management",
    product_24: "Malicious Bot Detection & Mitigation",
    product_25: "SSL",
    product_26: "Autumated SSL certificate deployment",
    product_27: "Access Control",
    product_28: "Multi-layer access control",
    product_29: "Media Security",
    product_30: "DRM",
    product_31: "Time-stamp",
    product_32: "Data Intelligence",
    product_33: "Real-Time Performance Monitoring, Network Layer Analytics, App & Live Streaming Performance Monitoring, Layer3/4/7 Attack Analytics & Alerting",
    product_34: "Real-Time Performance Monitoring",
    product_35: "Real-time monitoring is the process of collecting and storing performance metrics for data as it traverses your network. It involves polling and streaming data from infrastructure devices so that you know how your networks, applications, and services are performing.",
    product_36: "Network Layer Analytics",
    product_37: "Networks are the backbone of every business. Even in small or enterprise-level businesses, the loss of productivity during a network outage can result in hefty damages. Network monitoring solutions helps you anticipate potential outages and address network problems proactively. This helps in maintaining a congestion-free network that keeps your business up and running. This can be achieved with the help of network monitoring tools. ",
    product_38: "App & Live Streaming Performance Monitoring",
    product_39: "Application performance monitoring (APM) for modern, cloud-native environments extends observability beyond system availability and service performance and response times. Automatic and intelligent observability helps organizations improve user experiences at the scale of modern computing.",
    product_40: "Layer3/4/7 Attack Analytics & Alerting",
    product_41: "Security systems create alerts for countless abnormalities, but understanding when a suspicious alert is an actual threat is far more complex. Attack Analytics, by Imperva, is the key to understanding the alerts generated by your Web Application Firewall and prioritizing incidents that need investigation and remediation.",
  },
  partnersPage: {
    partners_1: "Service for All",
    partners_2: "SMES",
    partners_3: "Saas",
    partners_4: "Online Gaming",
    partners_5: "Media Entertainment",
    partners_6: "Service for All",
    partners_7: "From individual bloggers to fortune 500 enterprises, we provide our full attention to each and every client who is eager to thrive and win.",
    partners_8: "SMES",
    partners_9: "We tailor the most suitable services for SMEs from all industries to optimize cost and efficiency, reduce risk, and enhance customer experience while delivering insights faster.",
    partners_10: "Saas",
    partners_11: "Ensuring secure, speedy, and dependable user experiences for your SaaS application's end users on a global scale necessitates a coordinated approach.Our suite of state-of-the-art and user-friendly products empowers SaaS providers to deliver market-leading apps with top-notch security and performance.",
    partners_12: "Online Gaming",
    partners_13: "The smoothness of the connection experience is the first key to the game experience. We understand that games of all sizes need to provide the best and extraordinary experience to many players. Support cross-platform, cross-region, and cross-device to ensure that the game and the player are closer.",
    partners_14_1: "Media",
    partners_14_2: "Entertainment",
    partners_15: "Planned website, video streaming or live video, providing customers with complete consulting services for various platform clients. Allows you to quickly transfer and deploy services, and adjust them as needed in real time. Together to provide the best audio, video and video services on the client side.",
  },
  about: {
    about_1: "About Siraya",
    about_2: "Mission & Vision",
    about_3: "With over 15 years of experience in web performance and security, Siraya Technologies is the lighthouse helping your online businesses navigate safely and smoothly in the ever-changing cyber world.",
    about_4: "Customer-centric",
    about_5: "Innovative",
    about_6: "Vendor Agnostic",
    about_7: "Simplistic",
    about_8: "Contact Sales",
    about_9: "We are customer obsessed and want to help you. Getting in touch with our Global Sales team is simple and fast. Just complete the form provided and we will contact you shortly.",
  }
};